### ISSUE TITLE
En libro de clases, se crean 10 Observaciones en vez de 1, para 2 primeros alumnos.

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#1]
Versión en que defecto fué encontrado (está en el tag title del html, sitúe el cursor del mouse sobre la pestaña o ventana del navegador y en el tooltip que se despliega anote el número a la derecha del texto "CloudEduca::"):
v0.6

Localización del defecto (Módulo y/o submódulo o menú):
En módulo Libro de clases, menú Observaciones, agregar Observación.

Descripción del defecto:
Al intentar agregar una nueva observación para un determinado alumno localizado en la primera o segunda fila del data grid, la cantidad de observaciones de ese alumno se incrementa en 10 en vez de en 1.
Finalmente si se ha seleccionado un filtro adicional, al crear la observación se pierde ese filtro, volviendo a cargarse el módulo filtrado por defecto.

Pasos para replicar defecto:
Siga los siguientes pasos para replicar el defecto:
1.- Logueado como usuario "test", desde cualquier módulo o menú de la aplicación, dirigirse al tab "Libro de clases".
2.- En el módulo que se carga con el primer filtro en "Observaciones" dejar todo por defecto y no aplicar ningún filtro adicional.
3.- Click en botón "Agregar Observación" para el alumno en la primera fila de la grilla (u opcionalmente la segunda, el defecto se presenta en ambos), el Alumno es "Anibal Juan Perez Perez" (u opcionalmente "Daniel Villegas"). En la venta que se despliega, cree una nueva observación (puede ser negativa o positiva) e ingrese cualquier texto en el textbox.
4.- La aplicación ha incrementado el valor de la cantidad de observaciones en 10, en vez de en 1.

**Comment by maximolira** [comment]
corregida en version 0.6.1.1
