### ISSUE TITLE
Bug Libro de Clase ( versión sistema  v0.6.3) (fecha publicación 29-01-2015)

### ISSUE THREAD

**Issue by NickoBarrios** [aintriago/nubEducacion#11]
Libro de Clase
1.- Observaciones
1.1.- La Lista de cursos debe iniciar en el primer registro, ya que con esto evitamos que se muestren todos los alumnos que el profesor tiene a cargo.
1.2.- El nombre de los alumnos debe estar todos juntos (nombres y apellidos)
2.- Asistencia.
2.1.- La Lista de cursos debe iniciar en el primer registro, ya que con esto evitamos que se muestren todos los alumnos que el profesor tiene a cargo.
2.2.- El formato de fecha debe ser DD-MM-YYYY
2.3.- Falta que muestre el mes  con palabra, aparte del día
2.4.- El porcentaje se muestra es mensual y se calcula por la cantidad de días del mes  
2.5.- Los nombre de porcentaje es  (Asistente  AS  e  Inasistencia  IN)
2.6.- Ingresar asistencia: 
2.6.1.- Una vez que selecciono un curso y creo la asistencia, este debe sincronizar con la lista de curso del filtro 
2.6.2.- No le pone el Check a la lista de alumnos  esto pasa cunado creo por primera vez presente a los alumnos, luego vuelvo a ingresar a asistencia y los dejo a todos ausente , después  ingreso nuevamente la asistencia y los dejo presente este no le pone el check a la lista de alumnos.
2.7.- Es posible de poner el porcentaje de  asistencia  por día 
3.- Comportamiento 
3.1.- La cantidad alumnos que se deben mostrar es de 50 alumnos.

**Comment by davavillerga** [comment]
Múltiples defectos reportados en el mismo issue, se debería reportar un sólo defecto ó solicitud de mejora en cada issue creado, utilizando para ello la plantilla correspondiente:
Defectos= https://drive.google.com/open?id=0B1icHaGYMq3PdUFTQlRBRzYyZ2s&authuser=0

Mejoras/Sugerencias= https://drive.google.com/open?id=0B1icHaGYMq3PanZ4RkJISFM3LVU&authuser=0
