### ISSUE TITLE
Planificacion: Al crear nueva Unidad, valores seleccionados en filtros nivel y asignatura no persisten a modal newUnidad

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#13]
##### Versión en que el defecto fué encontrado (está en el tag title del html, sitúe el cursor del mouse sobre la pestaña o ventana del navegador y en el tooltip que se despliega anote el número a la derecha del texto "CloudEduca::"):

v0.6.3
##### Localización del defecto (Módulo y/o submódulo o menú):

En módulo **PLANIFICACION** , modal: _loadHome/newUnidad_, botón id=_"CrearUnidadButton"_.
##### Descripción del defecto:

Al querer crear una nueva unidad habiendo previamente filtrado los valores para usuario, nivel y asignatura a través del botón _“Crear Unidad”_, los valores seleccionados en los filtros no son persistidos hacia el modal _newUnidad_ causando un reinicio a los valores por defecto para los filtros _“nivel”_ y _“asignatura”_ pero del modal _newUnidad_. 
##### Funcionalidad esperada:

En el caso de que en el modal loadHome se hayan seleccionado valores en alguno de los filtros definidos allí, si se desea crear una nueva Unidad mediante el botón, se espera que la pantalla siguiente (modal newUnidad) venga prefiltrada con esos valores previamente seleccionados.
##### Pasos para replicar defecto:

1.- Log in en plataforma usando usuario “test”
2.- Navegar a pestaña Planificación
3.- Filtrar los valores de “nivel” a “Primero Básico” Y “asignatura” a “Educación Física y Salud”
4.- Click en botón “Crear Unidad”.
5.- Note que los filtros “nivel” y “asignatura” en modal newUnidad están seteados por defecto y se deben volver a seleccionar.

**Comment by maximolira** [comment]
Arreglada en proxima version
