### ISSUE TITLE
Planificación: Al crear una copia de una Unidad habiendo seleccionado valores para filtros nivel y asignatura; una vez creada la copia, se vuelve al modal load_Home con los valores de los filtros seteados por defecto

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#15]
##### Versión en que el defecto fué encontrado (está en el tag title del html, sitúe el cursor del mouse sobre la pestaña o ventana del navegador y en el tooltip que se despliega anote el número a la derecha del texto "CloudEduca:"):

v0.6.3
##### Localización del defecto (Módulo y/o submódulo o menú):

En módulo **PLANIFICACION**, modal: _loadHome_, botón _id="11Planificacion_Copia"_
##### Descripción del defecto:

Al querer crear una nueva unidad creando una copia a partir de una existente, y habiendo previamente filtrado los valores para _nivel y asignatura_ a través del botón _“Copiar”_, los valores seleccionados en los filtros se pierden una vez realizada la operación de copiado; Al hacer click en el botón "Guardar", el sistema es redireccionado nuevamente al modal _loadHome_ dandose reinicio a los valores por defecto para los filtros “nivel” y “asignatura”.
##### Funcionalidad esperada:

En el caso de que en el modal loadHome se hayan seleccionado valores en alguno de los filtros definidos allí y luego si se quiere realizar una copia de una unidad, se espera que al finalizar la operación de copiado, se vuelva al modal loadHome pero que esta vez en la grilla de datos de ese modal los datos vengan prefiltrados con los valores previamente seleccionados.
##### Pasos para replicar defecto:

Siga los siguientes pasos para replicar el defecto:
1.- Log in en plataforma usando usuario “test”
2.- Navegar a pestaña Planificación
3.- Filtrar los valores de “nivel” a “Primero Básico” Y “asignatura” a “Educación Física y Salud”
4.- Click en botón “Copiar” de alguna de las filas en la grilla.
5.- En el diálogo que aparece, darle un nombre a la copia a crear y click en botón _"Guardar"_.
5.- Note que los filtros “nivel” y “asignatura” en modal newUnidad están seteados por defecto y se deben volver a seleccionar.

**Comment by maximolira** [comment]
corregida en siguiente version
