### ISSUE TITLE
Planificación: Al exportar una Unidad a PDF se muestran los ID de los objetivos de aprendizaje de la unidad y de las clases.

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#6]
Versión en que el defecto fué encontrado:
v0.6.1.1
Localización del defecto (Módulo y/o submódulo o menú):
En módulo PLANIFICACION, botón VER.
.../Demo/planificacion/verPDFUnidad

Descripción del defecto:
Al querer ver una planificación completa (Unidad y sus clases), hay información errónea en el PDF resultante. En la sección Objetivos de aprendizaje tanto de la unidad como de las clases en esa unidad, al lado izquierdo aparece un código númerico (ID), en vez del código del ministerio para ese objetivo (por ejemplo: AR01 OA 03).

Funcionalidad esperada:
Se esperaría que en el PDF resultante saliera al lado de cada objetivo tanto de una clase como de una unidad, el código del ministerio asociado a ese objetivo.

Pasos para replicar defecto: 
Siga los siguientes pasos para replicar el defecto:
1.- Login a la app con user test
2.- Navegar hasta pestaña Planificación
3.- En la grilla mostrada con las Unidades disponibles, click en el botón VER en una de ellas.
4.- Observar lo descrito en el PDF resultante.

**Comment by maximolira** [comment]
Esto estará resuelto en la próxima version
