### ISSUE TITLE
Planificación: Al exportar una Unidad o  Clase a PDF se muestran las etiquetas HTML insertas Actividades Metodologicas de la clase o Unidad

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#7]
Versión en que el defecto fué encontrado:
v0.6.1.1
Localización del defecto (Módulo y/o submódulo o menú):
En módulo PLANIFICACION, botón VER.
.../Demo/planificacion/verPDFUnidad    y
.../Demo/planificacion/verPDFClases

Descripción del defecto:
Al exportar una clase o una unidad completa a PDF usando el boton VER, cualquier texto que contenga tags HTML esos tags no son interpretados sino que quedan como texto plano junto al texto original.

Funcionalidad esperada:
Se esperaría que en el PDF resultante saliera al lado de cada objetivo tanto de una clase como de una unidad, el código del ministerio asociado a ese objetivo.

Pasos para replicar defecto: 
Siga los siguientes pasos para replicar el defecto:
1.- Login a la app con user test
2.- Navegar hasta pestaña Planificación
3.- En la grilla mostrada con las Unidades disponibles, click en el botón CLASES de la unidad de nombre "Unidad I - Artes Visuales - 3°A".
4.- En la grilla con las clases de esa unidad, hacer click en boton VER de cualquiera de las dos.
5.- Observar lo descrito en el PDF resultante, en las actividades metodológicas

**Comment by davavillerga** [comment]
Encontré esto en la documentación de FPDF, al parecer alguien ya se dio la lata y subió un script, que permite llamar a una función writeHTML (que se podría reemplazar por la llamada a Write() o Cell() )

http://www.fpdf.org/en/script/script42.php

**Comment by maximolira** [comment]
Esto estará reparado en la próxima version
