### ISSUE TITLE
RFE - Imagen de Fondo de CloudEduca

### ISSUE THREAD

**Issue by davavillerga** [aintriago/nubEducacion#8]
RFE(Request For Enhancement) CloudEduca

Módulo/Funcionalidad afectado:
Todos.

Descripción:
Se abre este thread para cubrir la configuración de la imagen de fondo del sistema.
Se ha propuesto la imagen en el link más abajo.

Justificación:
Forma parte del plan, seteo de aspectos de diseño del GUI.

Prioridad MoSCoW (http://en.wikipedia.org/wiki/MoSCoW_method):
S(Should).

Archivos Adjuntos:
- https://drive.google.com/open?id=0B1icHaGYMq3PRHVRbVotWDQwSVNhWlhUX3NpTmpzNnpKVjBR&authuser=0

**Comment by maximolira** [comment]
Imagen cambiada en version 0.6.3
