### ISSUE TITLE
Error en Planificaccion (Fecha publicacion 28-01-2015)

### ISSUE THREAD

**Issue by NickoBarrios** [aintriago/nubEducacion#9]
1.- Crear Unidad
     1.1- El formato de la fecha debe ser DD-MM-YYYY
     2.2- Se debe sincronizar la lista de valores de curriculum en linea y la edicion de la unidad
2.- Crear Clase
      2.1.- El formato de la fecha debe ser DD-MM-YYYY
      2.2.- Permitio guardar y no valido que estuviera un obejetivo y actidad selecionada
3.- Copiar clase
     3.1.- Por defecto debe apareser la primera lista con la unidad lacual pertenese la clase..
     3.2.- Cuando copio una clase, esta no esta copiando los objetivos y actividaes selecionada en la case origen
4.- Comportamiento
      4.1.- Cuando agrego un objetivo mas en la unidad, las clases pierden todos los objetivos y las actividad previasmente seleccionada
      4.2.- Seleccionar todo objetivo, si quiero seleccionar todos los objetivos este seleciona los objetivo y las actividades.
      4.3.- Seleccionar todo Actividad, Este no seleciona nada

**Comment by NickoBarrios** [comment]
Este bug esta asociado al anterior
para el punto 2.2 --> no va, ya que esta correcto como esta actualmente
Para el Punto 3.2 --> cuando se copie clases en la misma unidad este debe copiar los objetivos y las actividades.... cuando se copia clase a otra unidad se debe copiar estos objetivos y las clases a la unidad y a la clase... siempre y cuando la unidad no tenga seleccionado los mismos objetivos y actividades

**Comment by maximolira** [comment]
Se debe utilizar los formatos y templates definidos para levantar defectos
